# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: L4D2_RPG_BLOCKER

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  
defaults:
  run:
    working-directory: L4D2_RPG_BLOCKER

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Cache Dependencies
      uses: actions/cache@v3
      id: python-cache
      with:
        path: ${{ env.pythonLocation }}/lib/python3.10/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install steam
        pip install python-a2s
        pip install fuzzywuzzy[speedup]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Github Scan Action
      run: |
        python github_actions.py
    - name: Auto Commit Push
      run: |
        git config --local user.email "razerdp123@gmail.com"
        git config --local user.name "razerdp"
        git add .
        git commit -m "update" -a
        git remote set-url origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
        git push
